---
title: "README"
author: "Bob Rudis"
date: August 25, 2014
output:
  md_document:
    variant: markdown_github
---

statebins is an alternative to choropleth maps for US States

The following functions are implemented:

- `statebins` -
- `statebins_continuous` -

### News

- Version `1.0.0` released

### Installation

```{r eval=FALSE}
devtools::install_github("hrbrmstr/statebins")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
options(width=120)
```

### Usage

```{r message=FALSE}
library(statebins)

# current verison
packageVersion("statebins")

# the original wapo data

dat <- read.csv("http://www.washingtonpost.com/wp-srv/special/business/states-most-threatened-by-trade/states.csv?cache=1", stringsAsFactors=FALSE)

gg <- statebins(dat, "state", "avgshare94_00", breaks=4, 
                labels=c("0-1", "1-2", "2-3", "3-4"),
                legend_title="State Groups", font_size=3, 
                brewer_pal="Blues", text_color="black", 
                plot_title="1994-2000", title_position="bottom")

gg

gg2 <- statebins_continuous(dat, "state", "avgshare01_07",
                            legend_title="State Data", legend_position="top",
                            brewer_pal="OrRd", text_color="black", font_size=3, 
                            plot_title="2001-2007", title_position="bottom")

gg2

gg3 <- statebins_continuous(dat, "state", "avgshare08_12",
                            legend_title="States", legend_position="none",
                            brewer_pal="Purples", text_color="black", font_size=3, 
                            plot_title="2008-2012", title_position="bottom")

gg3

```

### Test Results

```{r}
library(statebins)
library(testthat)

date()

test_dir("tests/")
```

